<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Bondy.Contracts\Bondy.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Bondy.ServiceDefaults\Bondy.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\shared\Bondy.SharedKernel.Api\Bondy.SharedKernel.Api.csproj" />
    <ProjectReference Include="..\Mail.Application\Mail.Application.csproj" />
    <ProjectReference Include="..\Mail.Infrastructure\Mail.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="uploads\" />
  </ItemGroup>

</Project>
