// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260121095203_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_accounts_user_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.ApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedPaths")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("allowed_paths");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key_id");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key_prefix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_email");

                    b.Property<int?>("RateLimitPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_plan_id");

                    b.Property<DateTimeOffset?>("RevokeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoke_at");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RotateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotate_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_id");

                    b.HasIndex("RevokeReason")
                        .HasDatabaseName("idx_api_keys_revoke_reason");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("idx_api_keys_active_exp");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.OtpCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purpose");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_otp_codes");

                    b.HasIndex("SubjectId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ux_active_otp_per_pre_reg")
                        .HasFilter("active = TRUE");

                    b.ToTable("otp_codes", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.PreRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean")
                        .HasColumnName("gender");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_pre_registrations");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_pre_registrations_email");

                    b.ToTable("pre_registrations", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("idx_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("user_id", "role_id")
                        .HasName("pk_user_roles");

                    b.HasIndex("role_id")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.Account", b =>
                {
                    b.HasOne("Identity.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_users_user_id");

                    b.OwnsOne("Identity.Domain.ValueObjects.HashedValue", "PasswordHash", b1 =>
                        {
                            b1.Property<long>("AccountId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password_hash");

                            b1.HasKey("AccountId");

                            b1.ToTable("accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_accounts_accounts_id");
                        });

                    b.Navigation("PasswordHash");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.ApiKey", b =>
                {
                    b.OwnsMany("Identity.Domain.ValueObjects.Scope", "Scopes", b1 =>
                        {
                            b1.Property<long>("api_key_id")
                                .HasColumnType("bigint")
                                .HasColumnName("api_key_id");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("scope");

                            b1.HasKey("api_key_id", "Value");

                            b1.ToTable("api_key_scopes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("api_key_id")
                                .HasConstraintName("fk_api_key_scopes_api_keys_api_key_id");
                        });

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("Identity.Domain.Entities.OtpCode", b =>
                {
                    b.OwnsOne("Identity.Domain.ValueObjects.HashedValue", "CodeHash", b1 =>
                        {
                            b1.Property<long>("OtpCodeId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("code_hash");

                            b1.HasKey("OtpCodeId");

                            b1.ToTable("otp_codes");

                            b1.WithOwner()
                                .HasForeignKey("OtpCodeId")
                                .HasConstraintName("fk_otp_codes_otp_codes_id");
                        });

                    b.Navigation("CodeHash")
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.PreRegistration", b =>
                {
                    b.OwnsOne("Identity.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<long>("PreRegistrationId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("text")
                                .HasColumnName("middle_name");

                            b1.HasKey("PreRegistrationId");

                            b1.ToTable("pre_registrations");

                            b1.WithOwner()
                                .HasForeignKey("PreRegistrationId")
                                .HasConstraintName("fk_pre_registrations_pre_registrations_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Identity.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Role", b =>
                {
                    b.OwnsMany("Identity.Domain.ValueObjects.Scope", "Scopes", b1 =>
                        {
                            b1.Property<long>("role_id")
                                .HasColumnType("bigint")
                                .HasColumnName("role_id");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("scope");

                            b1.HasKey("role_id", "Value")
                                .HasName("pk_role_scopes");

                            b1.HasIndex("role_id")
                                .HasDatabaseName("ix_role_scopes_role_id");

                            b1.ToTable("role_scopes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("role_id")
                                .HasConstraintName("fk_role_scopes_roles_role_id");
                        });

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Identity.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("text")
                                .HasColumnName("middle_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsMany("Identity.Domain.ValueObjects.Scope", "DeniedScopes", b1 =>
                        {
                            b1.Property<long>("user_id")
                                .HasColumnType("bigint")
                                .HasColumnName("user_id");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("scope");

                            b1.HasKey("user_id", "Value")
                                .HasName("pk_user_denied_scopes");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_user_denied_scopes_user_id");

                            b1.ToTable("user_denied_scopes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_user_denied_scopes_users_user_id");
                        });

                    b.OwnsMany("Identity.Domain.ValueObjects.Scope", "GrantedScopes", b1 =>
                        {
                            b1.Property<long>("user_id")
                                .HasColumnType("bigint")
                                .HasColumnName("user_id");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("scope");

                            b1.HasKey("user_id", "Value")
                                .HasName("pk_user_granted_scopes");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_user_granted_scopes_user_id");

                            b1.ToTable("user_granted_scopes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_user_granted_scopes_users_user_id");
                        });

                    b.Navigation("DeniedScopes");

                    b.Navigation("GrantedScopes");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role");

                    b.HasOne("Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
