CREATE DATABASE identity;
CREATE DATABASE mail;

GRANT ALL PRIVILEGES ON DATABASE identity TO bondy;
GRANT ALL PRIVILEGES ON DATABASE mail TO bondy;

\connect identity
CREATE EXTENSION IF NOT EXISTS vector;

\connect mail
CREATE EXTENSION IF NOT EXISTS vector;