<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="8.0.2" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.22" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Scriban" Version="6.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Bondy.SharedKernel.Infrastructure\Bondy.SharedKernel.Infrastructure.csproj" />
    <ProjectReference Include="..\Mail.Application\Mail.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Templates\" />
  </ItemGroup>

</Project>
